### ISSUE TITLE
Expresividad

### ISSUE THREAD

**Issue by rgonzalezt** [priquelme/PdeP_Lunes_K2002_2021#1]
Cada `Participante` puede tener:
- Muchas acciones por lo que lo ideal es que ese campo se llame `acciones` y no `accion`.
- Muchas propiedades, de vuelta, lo ideal es que ese campo se llame `propiedades` y no `propiedad`.

Sino se hace muy confuso seguir el código.

**Corregir lo antes mencionado.**

**Comment by priquelme** [comment]
Se subió posible solución.
