### ISSUE TITLE
Funciones que "cambian" propiedades

### ISSUE THREAD

**Issue by rgonzalezt** [priquelme/PdeP_Lunes_K2002_2021#2]
Estás repitiendo lógica a la hora de cambiar propiedades del `Participante`. 
Por eso es que solemos crear las funciones `mapXX` (o `modificarXX` o `cambiarXX`) haciéndolas lo más genéricas posibles para que sirvan en diferentes casos. Por esto es que les solemos pasar una función y un jugador.

**Crear estas funciones y aplicalas en tu solución para no repetir lógica.**

**Comment by priquelme** [comment]
Se subió posible solución.

**Comment by rgonzalezt** [comment]
Genial que hayas creado esas funciones. Ojo en el caso de cambiar la táctica en la función `pasarPorElBanco` porque no le agrega una táctica a la persona, sino que la reemplaza por `"Comprador compulsivo"`. Vos hiciste:

```haskell
pasarPorElBanco = mapTactica ((++) "Comprador Compulsivo") . mapCantidadDinero (+ 40) 
```

Pero deberías haber hecho:

```haskell
pasarPorElBanco = mapTactica (const "Comprador Compulsivo") . mapCantidadDinero (+ 40) 
```

De esa forma reemplazamos la táctica, no la agregamos. 

No hace falta que corrijas este punto pero sí tenelo en cuenta para el parcial. 
Cuando leas este comentario, cerrá el issue. 🌈
