### ISSUE TITLE
Cobrar alquileres (poca declaratividad)

### ISSUE THREAD

**Issue by rgonzalezt** [priquelme/PdeP_Lunes_K2002_2021#5]
Tu solución tiene muchos pasos algorítmicos que podríamos solucionar delegando apropiadamente. 
Para este punto lo ideal es delegar en partecitas que nos van a ayudar a resolver el problema:

- Tenemos que fijarnos si una propiedas _es cara o barata_. Para eso sabemos que si su valor es menor a 150, es barata. En caso contrario será cara.
- Luego, lo que nos interesaría saber es el precio del aquiler según esta condición. Para eso podríamos crear la función `precioAlquiler` que, según si es cara o barata nos devuelva `10` o `20`. Las guardas nos serán de gran ayuda en esta parte.
- Finalmente, el `alquilerPropiedades` sería trivial definirlo con lo anterior ya que sólamente deberíamos sumar los valores del precio del alquiler de las propiedades de una persona. Tené en cuenta que podemos "convertir" esas propiedades a sus precios correspondientes con una función de orden superior.

**Corregir este punto con lo antes mencionado.**

**Comment by priquelme** [comment]
Se subió posible solución.

**Comment by rgonzalezt** [comment]
Este punto lo veo igual que antes. Una forma más declarativa de resolverlo, podría ser sería la siguiente:

```haskell
esPropiedadBarata :: Propiedad -> Bool
esPropiedadBarata propiedad = precioPropiedad propiedad < 150

precioAlquiler :: Propiedad -> Int
precioAlquiler propiedad
  | esPropiedadBarata propiedad = 10
  | otherwise                   = 20

ingresosPorAlquileres :: Persona -> Int
ingresosPorAlquileres persona = sum . map precioAlquiler . propiedades $ persona

cobrarAlquileres :: Accion
cobrarAlquileres persona = cambiarDinero ((+).ingresosPorAlquileres $ persona) persona
```

Tenelo en cuenta para el parcial. No hace falta que corrijas tu solución. Cuando leas este comentario, cerrá el issue. 🌈
